import type { Metadata } from "next";
import BaseLayout from "@/components/base-layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <BaseLayout>
      {children}
      {children}
    </BaseLayout>
  );
}
